{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE RecordWildCards #-}

module Types where

import Data.Char (isSpace)
import Data.List (intercalate)
import Data.List.Split (splitOn)
import Data.Text qualified as Text
import Data.Text.Lazy (Text)
import Database.SQLite.Simple.FromField (ResultError (ConversionFailed), fromField, returnError)
import Database.SQLite.Simple.FromRow (FromRow (..), field, fieldWith)
import Text.Regex.PCRE.Heavy (Regex, gsub, re)


newtype Wort = Wort {unWort :: String} deriving (Eq, Ord)


compareWordsCaseInsensitive :: Wort -> Wort -> Ordering
compareWordsCaseInsensitive (Wort a) (Wort b) =
    Text.toLower (Text.pack a) `compare` Text.toLower (Text.pack b)


instance Show Wort where
    show (Wort w) = w


newtype Mp3Url = Mp3Url Text deriving (Eq, Show)


data SearchResult
    = PronFound Mp3Url
    | PronNotAvailable
    | NotFound
    | Unknown
    deriving (Eq)


instance Show SearchResult where
    show = \case
        PronFound mp3Url -> show mp3Url
        PronNotAvailable -> "Pron N/A"
        NotFound -> "Not in dictionary"
        Unknown -> "UNEXPECTED ERROR"


data AnkiNote = AnkiNote
    { noteId :: Int
    , noteLang1 :: String
    , noteLang2 :: String
    , noteExamples :: String
    , noteYes :: String
    , noteTags :: String
    }
    deriving (Show)


instance FromRow AnkiNote where
    fromRow = do
        noteId <- field
        (noteLang1, noteLang2, noteExamples, noteYes) <- fieldWith $ \f -> do
            flds <- fromField f
            case splitOn "\US" flds of
                [l1, l2, ex, y] -> pure (l1, l2, ex, y)
                fields ->
                    returnError ConversionFailed f $
                        "Expected 4 fields, but got " <> show (length fields) <> ": " <> show fields
        noteTags <- field
        pure $ AnkiNote{..}


getFields :: AnkiNote -> [String]
getFields note = [noteLang1 note, noteLang2 note, noteExamples note, noteYes note]


getFieldsWithAddedMp3Reference :: FilePath -> AnkiNote -> String
getFieldsWithAddedMp3Reference mp3File note =
    let lang2WithMp3Ref = noteLang2 note <> "[sound:" <> mp3File <> "]"
     in intercalate "\US" [noteLang1 note, lang2WithMp3Ref, noteExamples note, noteYes note]


getFieldsWithAddedExample :: String -> FilePath -> AnkiNote -> String
getFieldsWithAddedExample sentence mp3File note =
    -- Using <em> is kind of hack to distinguish autogenerated examples from manually added ones.
    let example = "<em>" <> sentence <> "[sound:" <> mp3File <> "]</em>"
     in intercalate "\US" [noteLang1 note, noteLang2 note, example, noteYes note]


-- | Primary deutsch word represented by the note (only valid for cards with 'wort' tag)
extractWord :: AnkiNote -> Wort
extractWord =
    Wort
        . deleteSpacesAndSlashes
        . deleteArticles
        . deletePartAfterDash
        . deleteSound
        . deleteThingsInParens
        . noteLang2
  where
    deleteSound = delRegex [re|\[sound:.*\.mp3\]|]
    deleteThingsInParens = delRegex [re|\([^\)]*\)|]
    deletePartAfterDash = delRegex [re| - .*|]
    deleteArticles s = let ws = words s in if length ws > 1 then last ws else s
    deleteSpacesAndSlashes = filter (\c -> not (isSpace c) && c /= '/')
    delRegex :: Regex -> String -> String
    delRegex regex = gsub regex ""
